# Generated by Django 5.2 on 2026-05-27 15:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID4 primary key. Never sequential, never guessable.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Immutable creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp.')),
                ('table_name', models.CharField(help_text="Database table that was affected. E.g., 'activities_activityrecord'.", max_length=100)),
                ('record_id', models.UUIDField(blank=True, help_text='UUID of the affected record. NULL for bulk operations affecting multiple records.', null=True)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Soft Delete'), ('review_transition', 'Review State Transition'), ('bulk_approve', 'Bulk Approve'), ('bulk_reject', 'Bulk Reject'), ('bulk_flag', 'Bulk Flag'), ('ingestion', 'Data Ingestion'), ('recalculation', 'Emission Recalculation'), ('login', 'User Login'), ('logout', 'User Logout')], db_index=True, max_length=30)),
                ('changed_fields', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('performed_by', models.ForeignKey(blank=True, help_text='User who performed the action. NULL if system-initiated or user was deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log Entry',
                'verbose_name_plural': 'Audit Log Entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['table_name', 'record_id'], name='audit_audit_table_n_dc0494_idx'), models.Index(fields=['organization_id', 'action'], name='audit_audit_organiz_775090_idx'), models.Index(fields=['performed_by', 'created_at'], name='audit_audit_perform_1898ca_idx')],
            },
        ),
    ]
