# Generated by Django 5.2 on 2026-05-27 15:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID4 primary key. Never sequential, never guessable.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Immutable creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft-deletion flag. True = logically deleted, physically preserved.')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('source_system', models.CharField(choices=[('sap', 'SAP'), ('utility', 'Utility Portal'), ('travel', 'Concur/Navan'), ('manual', 'Manual Entry')], db_index=True, help_text='Which external system produced the original data.', max_length=20)),
                ('source_identifier', models.CharField(blank=True, db_index=True, help_text='Unique ID from source system. E.g., SAP Belegnummer, Concur expense ID, utility account+bill date.', max_length=255)),
                ('scope', models.CharField(choices=[('1', 'Scope 1 - Direct Emissions'), ('2', 'Scope 2 - Indirect Electricity'), ('3', 'Scope 3 - Value Chain')], db_index=True, help_text='GHG Protocol scope. Determines reporting bucket and audit requirements.', max_length=2)),
                ('scope_3_category', models.CharField(blank=True, choices=[('', 'Not Applicable'), ('3.1', '3.1 - Purchased Goods & Services'), ('3.2', '3.2 - Capital Goods'), ('3.3', '3.3 - Fuel & Energy Related (Not in Scope 1/2)'), ('3.4', '3.4 - Upstream Transport'), ('3.5', '3.5 - Waste'), ('3.6', '3.6 - Business Travel'), ('3.7', '3.7 - Employee Commuting'), ('3.8', '3.8 - Upstream Leased Assets')], db_index=True, default='', help_text='Specific Scope 3 category. Empty for Scope 1 and 2.', max_length=10)),
                ('activity_type', models.CharField(choices=[('stationary_fuel', 'Stationary Fuel Combustion'), ('mobile_fuel', 'Mobile Fuel Combustion'), ('purchased_electricity', 'Purchased Electricity'), ('purchased_heat_steam', 'Purchased Heat/Steam'), ('business_travel_flight', 'Business Travel - Flight'), ('business_travel_rail', 'Business Travel - Rail'), ('business_travel_car', 'Business Travel - Car/Rental'), ('business_travel_taxi', 'Business Travel - Taxi/Ride'), ('business_travel_hotel', 'Business Travel - Hotel')], db_index=True, help_text='Type of activity. Determines which emission factor to apply.', max_length=30)),
                ('activity_amount', models.DecimalField(decimal_places=6, help_text='Normalized activity quantity in base units. E.g., kg of fuel, kWh of electricity, km of flight.', max_digits=20)),
                ('activity_unit', models.CharField(choices=[('kwh', 'kWh'), ('kg', 'Kilogram (kg)'), ('km', 'Kilometer (km)'), ('night', 'Hotel night')], help_text='Base unit of the activity amount.', max_length=10)),
                ('period_start', models.DateField(db_index=True, help_text='Start of the activity period (inclusive). E.g., utility bill start date.')),
                ('period_end', models.DateField(db_index=True, help_text='End of the activity period (inclusive). E.g., utility bill end date.')),
                ('country', models.CharField(default='US', help_text='ISO-3166 country code where activity occurred. Determines which factor set applies.', max_length=2)),
                ('region', models.CharField(blank=True, help_text="Sub-national region for precise factor selection. E.g., eGRID subregion 'RFCW', or state 'TX'.", max_length=20)),
                ('fuel_type', models.CharField(blank=True, help_text="Standardized fuel type. E.g., 'diesel', 'natural_gas'. Used with IPCC/EPA factors.", max_length=20)),
                ('original_amount', models.DecimalField(blank=True, decimal_places=6, help_text='Quantity as originally reported (before unit conversion). E.g., 500 liters.', max_digits=20, null=True)),
                ('original_unit', models.CharField(blank=True, help_text="Original unit from source. E.g., 'liter', 'gal', 'm³'.", max_length=20)),
                ('conversion_note', models.TextField(blank=True, help_text="Human-readable explanation of unit conversion. E.g., '500 L × 0.845 kg/L = 422.5 kg'")),
                ('distance_band', models.CharField(blank=True, help_text="For flights: 'short', 'medium', 'long' per DEFRA classification.", max_length=20)),
                ('travel_class', models.CharField(blank=True, help_text="For flights: 'economy', 'business', 'first'.", max_length=20)),
                ('origin_location', models.CharField(blank=True, help_text='For travel: origin airport code, station name, or city.', max_length=100)),
                ('destination_location', models.CharField(blank=True, help_text='For travel: destination airport code, station name, or city.', max_length=100)),
                ('co2e_kg', models.DecimalField(blank=True, decimal_places=6, help_text='Total CO2 equivalent in kilograms. The number that goes to auditors.', max_digits=20, null=True)),
                ('co2e_calculation_audit', models.JSONField(blank=True, default=dict, help_text='Complete provenance of the CO2e calculation. Factor ID, math, rationale, timestamp.')),
                ('review_status', models.CharField(choices=[('pending', 'Pending Review'), ('flagged', 'Flagged'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', help_text='Current state in the analyst review workflow.', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Timestamp of review action.', null=True)),
                ('review_notes', models.TextField(blank=True, help_text="Analyst's free-text notes. E.g., 'Verified with facilities team - actual read, not estimated.'")),
                ('is_edited', models.BooleanField(default=False, help_text='True if this record has been modified after initial creation.')),
                ('edited_at', models.DateTimeField(blank=True, help_text='Timestamp of last edit.', null=True)),
                ('original_values', models.JSONField(blank=True, help_text='JSON snapshot of fields before they were edited. Enables before/after comparison.', null=True)),
                ('edit_reason', models.TextField(blank=True, help_text="Mandatory reason for edit. E.g., 'Corrected fuel type from gasoline to diesel per invoice.'")),
                ('is_estimated', models.BooleanField(default=False, help_text='For utility data: True if this bill was based on an estimated meter read.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text="Source-specific additional data. E.g., {'demand_kw': 450, 'utility_account': '12345'}.")),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(blank=True, help_text='User who made the last edit.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_activities', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(blank=True, help_text='Physical facility where the activity occurred. NULL for travel without fixed facility.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_records', to='facilities.facility')),
            ],
            options={
                'verbose_name': 'Activity Record',
                'verbose_name_plural': 'Activity Records',
                'ordering': ['-period_start', '-created_at'],
            },
        ),
    ]
