# Generated by Django 5.2 on 2026-05-27 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('ingestion', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activityrecord',
            name='ingestion_run',
            field=models.ForeignKey(help_text='The parent ingestion batch. PROTECT preserves audit trail even if run is deleted.', on_delete=django.db.models.deletion.PROTECT, related_name='activity_records', to='ingestion.ingestionrun'),
        ),
        migrations.AddField(
            model_name='activityrecord',
            name='organization',
            field=models.ForeignKey(help_text='The client organization that owns this record.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='activityrecord',
            name='raw_data_row',
            field=models.OneToOneField(blank=True, help_text='The exact raw source row. One-to-one because each raw row produces one activity record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='derived_activity_record', to='ingestion.rawdatarow'),
        ),
        migrations.AddField(
            model_name='activityrecord',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Analyst who approved/rejected/flagged this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activityrecord',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='activityrecord',
            index=models.Index(fields=['organization', 'scope', 'review_status'], name='activities__organiz_d4ea0c_idx'),
        ),
        migrations.AddIndex(
            model_name='activityrecord',
            index=models.Index(fields=['organization', 'period_start', 'period_end'], name='activities__organiz_cc3cc7_idx'),
        ),
        migrations.AddIndex(
            model_name='activityrecord',
            index=models.Index(fields=['organization', 'source_system', 'source_identifier'], name='activities__organiz_cd9d0b_idx'),
        ),
        migrations.AddIndex(
            model_name='activityrecord',
            index=models.Index(fields=['facility', 'review_status'], name='activities__facilit_3cf18d_idx'),
        ),
        migrations.AddConstraint(
            model_name='activityrecord',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='period_end_after_start', violation_error_message='Activity period end must be on or after period start.'),
        ),
    ]
