# Generated by Django 5.2 on 2026-05-27 15:00

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID4 primary key. Never sequential, never guessable.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Immutable creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft-deletion flag. True = logically deleted, physically preserved.')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text="Human-readable facility name, e.g., 'Houston Manufacturing Plant'", max_length=255)),
                ('sap_plant_code', models.CharField(blank=True, db_index=True, help_text='SAP Werk (plant) code. Used to map SAP export rows to facilities.', max_length=50)),
                ('sap_cost_center', models.CharField(blank=True, help_text='Optional SAP cost center for granular attribution.', max_length=50)),
                ('address_line_1', models.CharField(blank=True, max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state_province', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, db_index=True, help_text='Postal/ZIP code. Primary key for eGRID subregion lookup in the US.', max_length=20)),
                ('country', models.CharField(default='US', help_text='ISO-3166 country code.', max_length=2)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, help_text='WGS84 latitude. Used for precise eGRID subregion determination.', max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, help_text='WGS84 longitude.', max_digits=11, null=True)),
                ('utility_account_numbers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='Electric utility account numbers associated with this facility.', size=None)),
                ('utility_provider_name', models.CharField(blank=True, help_text="Name of electric utility (e.g., 'Pacific Gas & Electric').", max_length=255)),
                ('egrid_subregion', models.CharField(blank=True, db_index=True, help_text='EPA eGRID subregion override. If blank, uses Organization default.', max_length=10)),
                ('facility_type', models.CharField(blank=True, choices=[('manufacturing', 'Manufacturing'), ('office', 'Office'), ('warehouse', 'Warehouse'), ('data_center', 'Data Center'), ('retail', 'Retail'), ('other', 'Other')], help_text='Type of facility. Affects analyst expectations (e.g., data centers use lots of electricity).', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive facilities are excluded from new ingestion but preserved historically.')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='The client organization that owns this record.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Facility',
                'verbose_name_plural': 'Facilities',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['organization', 'sap_plant_code'], name='facilities__organiz_8166a8_idx'), models.Index(fields=['organization', 'postal_code'], name='facilities__organiz_8928ad_idx')],
            },
        ),
    ]
