# Generated by Django 5.2 on 2026-05-27 15:00

import apps.ingestion.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('facilities', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID4 primary key. Never sequential, never guessable.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Immutable creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft-deletion flag. True = logically deleted, physically preserved.')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('source_type', models.CharField(choices=[('sap', 'SAP - Fuel & Procurement'), ('utility', 'Utility - Electricity'), ('travel', 'Travel - Concur/Navan')], db_index=True, help_text='Which external system produced this data. Determines which parser to use.', max_length=20)),
                ('ingestion_method', models.CharField(choices=[('csv_upload', 'CSV File Upload'), ('json_upload', 'JSON File Upload'), ('manual_entry', 'Manual Data Entry'), ('api_pull', 'API Pull (Simulated)')], default='csv_upload', help_text='How the data entered our system. CSV upload is the realistic enterprise pattern.', max_length=20)),
                ('raw_file', models.FileField(help_text='The exact file as received from the client. Never modified after upload.', upload_to=apps.ingestion.models.raw_upload_path)),
                ('checksum', models.CharField(blank=True, help_text='SHA-256 hash of the uploaded file. Verifies storage integrity.', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('parsing', 'Parsing'), ('parsed', 'Parsed'), ('failed', 'Failed'), ('partial', 'Partial Success')], db_index=True, default='pending', help_text='Current state of this ingestion batch.', max_length=20)),
                ('total_rows', models.PositiveIntegerField(blank=True, help_text='Total rows detected in the source file.', null=True)),
                ('valid_rows', models.PositiveIntegerField(blank=True, help_text='Rows that passed validation and created ActivityRecords.', null=True)),
                ('invalid_rows', models.PositiveIntegerField(blank=True, help_text='Rows that failed validation (e.g., missing plant code, negative kWh).', null=True)),
                ('suspicious_rows', models.PositiveIntegerField(blank=True, help_text='Rows that parsed but triggered warnings (e.g., estimated utility read).', null=True)),
                ('error_summary', models.JSONField(blank=True, default=dict, help_text="Aggregated error counts by type. Example: {'missing_plant_code': 5, 'negative_kwh': 2}")),
                ('period_start', models.DateField(blank=True, help_text='Earliest activity period found in this batch.', null=True)),
                ('period_end', models.DateField(blank=True, help_text='Latest activity period found in this batch.', null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(blank=True, help_text='If the upload is specific to one facility (e.g., utility bill for Plant A).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingestion_runs', to='facilities.facility')),
                ('organization', models.ForeignKey(help_text='The client organization that owns this record.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ingestion Run',
                'verbose_name_plural': 'Ingestion Runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RawDataRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID4 primary key. Never sequential, never guessable.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Immutable creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft-deletion flag. True = logically deleted, physically preserved.')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('source_row_number', models.PositiveIntegerField(help_text='1-based row number in the source file. Helps analysts find the exact raw data.')),
                ('raw_payload', models.JSONField(help_text='Exact row data as received from source. Immutable after creation.')),
                ('parsed_status', models.CharField(choices=[('pending', 'Pending'), ('valid', 'Valid'), ('invalid', 'Invalid'), ('suspicious', 'Suspicious'), ('skipped', 'Skipped')], db_index=True, default='pending', help_text='Result of parsing this row.', max_length=20)),
                ('parse_errors', models.JSONField(blank=True, default=list, help_text='List of human-readable error/warning messages from the parser.')),
                ('source_identifier', models.CharField(blank=True, db_index=True, help_text='Extracted document/transaction ID from source. E.g., SAP Belegnummer, Concur expense ID.', max_length=255)),
                ('raw_period_start', models.DateField(blank=True, help_text='Extracted period start date from raw data.', null=True)),
                ('raw_period_end', models.DateField(blank=True, help_text='Extracted period end date from raw data.', null=True)),
                ('activity_record', models.OneToOneField(blank=True, help_text='The normalized ActivityRecord derived from this raw row. Null if parsing failed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_raw_data_row', to='activities.activityrecord')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('ingestion_run', models.ForeignKey(help_text='The parent ingestion batch this row belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='ingestion.ingestionrun')),
                ('organization', models.ForeignKey(help_text='The client organization that owns this record.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Raw Data Row',
                'verbose_name_plural': 'Raw Data Rows',
                'ordering': ['ingestion_run', 'source_row_number'],
            },
        ),
        migrations.AddIndex(
            model_name='ingestionrun',
            index=models.Index(fields=['organization', 'source_type', 'status'], name='ingestion_i_organiz_1d0f96_idx'),
        ),
        migrations.AddIndex(
            model_name='ingestionrun',
            index=models.Index(fields=['organization', 'created_at'], name='ingestion_i_organiz_e8422f_idx'),
        ),
        migrations.AddIndex(
            model_name='rawdatarow',
            index=models.Index(fields=['ingestion_run', 'parsed_status'], name='ingestion_r_ingesti_cd1ce3_idx'),
        ),
        migrations.AddIndex(
            model_name='rawdatarow',
            index=models.Index(fields=['organization', 'parsed_status'], name='ingestion_r_organiz_a323d0_idx'),
        ),
    ]
