# Generated by Django 5.2 on 2026-05-27 15:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID4 primary key. Never sequential, never guessable.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Immutable creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft-deletion flag. True = logically deleted, physically preserved.')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('epa_egrid', 'EPA eGRID'), ('defra', 'UK DEFRA'), ('ipcc', 'IPCC'), ('epa', 'EPA'), ('custom', 'Custom')], help_text='Authority that published this factor. Determines credibility with auditors.', max_length=20)),
                ('source_version', models.CharField(help_text="Specific vintage, e.g., 'eGRID2022', 'DEFRA_2025', 'IPCC_2019'.", max_length=50)),
                ('activity_type', models.CharField(choices=[('purchased_electricity', 'Purchased Electricity'), ('purchased_heat_steam', 'Purchased Heat/Steam'), ('stationary_fuel', 'Stationary Fuel Combustion'), ('mobile_fuel', 'Mobile Fuel Combustion'), ('business_travel_flight', 'Business Travel - Flight'), ('business_travel_rail', 'Business Travel - Rail'), ('business_travel_car', 'Business Travel - Car/Ground'), ('business_travel_taxi', 'Business Travel - Taxi/Ride'), ('business_travel_hotel', 'Business Travel - Hotel')], db_index=True, help_text='Category of activity this factor converts.', max_length=30)),
                ('region', models.CharField(db_index=True, help_text="Geographic code. For eGRID: subregion (RFCW). For travel: country (UK) or 'global'.", max_length=20)),
                ('fuel_type', models.CharField(blank=True, choices=[('diesel', 'Diesel'), ('gasoline', 'Gasoline/Petrol'), ('natural_gas', 'Natural Gas'), ('lpg', 'LPG'), ('jet_kerosene', 'Jet Kerosene'), ('fuel_oil', 'Fuel Oil'), ('coal', 'Coal'), ('', 'Not Applicable')], db_index=True, default='', help_text='Specific fuel type. Empty for electricity and general travel factors.', max_length=20)),
                ('distance_band', models.CharField(blank=True, choices=[('', 'Not Applicable'), ('short', 'Short Haul (< 500 km)'), ('medium', 'Medium Haul (500-3700 km)'), ('long', 'Long Haul (> 3700 km)'), ('domestic', 'Domestic'), ('international', 'International')], default='', help_text='For flight factors: distance category determines emission intensity.', max_length=20)),
                ('travel_class', models.CharField(blank=True, choices=[('', 'Not Applicable'), ('economy', 'Economy'), ('premium_economy', 'Premium Economy'), ('business', 'Business'), ('first', 'First Class'), ('average', 'Average/Unknown')], default='', help_text='For flights: emission factor varies by cabin class due to space allocation.', max_length=20)),
                ('co2e_kg_per_unit', models.DecimalField(decimal_places=10, help_text='Kilograms of CO2 equivalent per unit of activity. High precision for audit accuracy.', max_digits=20)),
                ('unit', models.CharField(choices=[('kwh', 'kWh'), ('liter', 'Liter (L)'), ('kg', 'Kilogram (kg)'), ('km', 'Kilometer (km)'), ('pax_km', 'Passenger-kilometer'), ('night', 'Hotel night'), ('m3', 'Cubic meter (m³)'), ('gal', 'US Gallon')], help_text='Unit of the activity amount that this factor applies to.', max_length=10)),
                ('effective_from', models.DateField(help_text='First date this factor vintage should be used (inclusive).')),
                ('effective_to', models.DateField(blank=True, help_text='Last date this factor vintage should be used (inclusive). Null means still active.', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Quick filter. False suppresses the factor from new calculations without deleting history.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extended provenance data: gas breakdown (CO2/CH4/N2O), RFI flags, density, etc.')),
                ('name', models.CharField(help_text="Descriptive name, e.g., 'DEFRA 2025 - Short-haul economy flight'", max_length=255)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Emission Factor',
                'verbose_name_plural': 'Emission Factors',
                'ordering': ['source', 'activity_type', 'region', '-effective_from'],
                'indexes': [models.Index(fields=['activity_type', 'region', 'fuel_type', 'is_active'], name='factors_emi_activit_b84742_idx'), models.Index(fields=['source', 'source_version'], name='factors_emi_source_eb0db6_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('activity_type', 'region', 'fuel_type', 'distance_band', 'travel_class', 'unit'), name='unique_active_factor_per_combo', violation_error_message='An active factor already exists for this activity/region/fuel combination.')],
            },
        ),
    ]
